INPUT_FILE = "input.txt"
INTERMEDIATE_PARSER_INPUT = "inter_parser_input.txt"
INTERMEDIATE_PARSER_OUTPUT = "inter_parser_output.txt"
CONSOLIDATED_PARSER_OUTPUT = "consolidated_parser_output.txt"
PROCESSED_PARSER_OUTPUT_FILE = "output.txt"
